name: Changeset Required (PR guard)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  require-changeset:
    name: Ensure changeset exists when src is modified
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }} # skip for drafts

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔎 Compute diff and check rules
        shell: bash
        env:
          BASE: ${{ github.event.pull_request.base.sha }}
          HEAD: ${{ github.sha }}
        run: |
          set -euo pipefail

          echo "Comparing changes from $BASE to $HEAD"
          git diff --name-only "$BASE"..."$HEAD" | tee changed_files.txt

          # Decide if this PR affects the *published package*.
          # Require a changeset when any of these change:
          #   - Library source
          #   - Packaging/build/type configs that can affect consumers
          NEEDS_CHANGESET=0
          while IFS= read -r f; do
            case "$f" in
              src/*) NEEDS_CHANGESET=1; break ;;
              package.json) NEEDS_CHANGESET=1; break ;;
              tsdown.config.ts) NEEDS_CHANGESET=1; break ;;
              tsconfig.json) NEEDS_CHANGESET=1; break ;;
              # Add more here if your release surface grows (e.g., exports maps, entry files)
            esac
          done < changed_files.txt

          if [ "$NEEDS_CHANGESET" -eq 0 ]; then
            echo "No release-affecting changes detected (playgrounds/test/docs/ci-only changes do not require a changeset)."
            exit 0
          fi

          # Require at least one changeset file in this PR
          if git diff --name-only "$BASE"..."$HEAD" -- .changeset/*.md | grep -q .; then
            echo "Changeset found — OK to proceed."
            exit 0
          fi

          echo "::error::This PR changes library/publishable files but has no changeset.
          Add one with:
            pnpm changeset
          Choose patch/minor/major and commit the generated file under .changeset/
          (Playgrounds, tests, docs, and CI-only changes do not need a changeset.)"
          exit 1
